import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const bundlePath = join(root, 'api/chat.js');
const bundle = readFileSync(bundlePath, 'utf8');

type ChatHandler = ((req: Request) => Promise<Response>) & {
  fetch: (req: Request) => Promise<Response>;
};

test('api/chat.js est un bundle ESM autonome (pas d’import relatif lib/chat)', () => {
  assert.match(bundle, /Generated by scripts\/bundle-api-chat\.mjs/);
  assert.doesNotMatch(bundle, /from\s+['"]\.\.\/lib\/chat\//);
  assert.doesNotMatch(bundle, /from\s+['"]\.\/handler['"]/);
  assert.doesNotMatch(bundle, /import\(\s*['"]\.\.\/lib\/chat\//);
  assert.match(bundle, /assistant_unavailable|X-Chat-Mode|text\/event-stream/);
});

test('le bundle n’utilise plus le modèle Groq retiré llama-3.1-8b-instant', () => {
  assert.doesNotMatch(bundle, /llama-3\.1-8b-instant/);
  assert.match(bundle, /openai\/gpt-oss-20b/);
});

test('GET /api/chat via le bundle renvoie { ok, mode }', async () => {
  const { default: handler } = (await import('../api/chat.js')) as { default: ChatHandler };
  const response = await handler.fetch(new Request('http://localhost/api/chat', { method: 'GET' }));
  assert.equal(response.status, 200);
  const body = (await response.json()) as { ok?: boolean; mode?: string };
  assert.equal(body.ok, true);
  assert.ok(body.mode === 'fallback' || body.mode === 'groq' || body.mode === 'gemini');
});

test('POST /api/chat via le bundle répond en fallback sans clé LLM', async () => {
  const prevGroq = process.env.GROQ_API_KEY;
  const prevGoogle = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  const prevGemini = process.env.GEMINI_API_KEY;
  delete process.env.GROQ_API_KEY;
  delete process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  delete process.env.GEMINI_API_KEY;

  try {
    const { default: handler } = (await import('../api/chat.js')) as { default: ChatHandler };
    const response = await handler.fetch(
      new Request('http://localhost/api/chat', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          messages: [{ role: 'user', content: 'Quels sont tes projets ?' }],
        }),
      })
    );

    assert.equal(response.status, 200);
    assert.equal(response.headers.get('x-chat-mode'), 'fallback');
    const text = await response.text();
    assert.match(text, /PICON|projet/i);
    assert.doesNotMatch(text, /MODULE_NOT_FOUND|assistant_unavailable/);
  } finally {
    if (prevGroq) process.env.GROQ_API_KEY = prevGroq;
    if (prevGoogle) process.env.GOOGLE_GENERATIVE_AI_API_KEY = prevGoogle;
    if (prevGemini) process.env.GEMINI_API_KEY = prevGemini;
  }
});

test('POST bundle répond Grosbit, formations et LinkedIn sans MODULE_NOT_FOUND', async () => {
  const prevGroq = process.env.GROQ_API_KEY;
  const prevGoogle = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  const prevGemini = process.env.GEMINI_API_KEY;
  delete process.env.GROQ_API_KEY;
  delete process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  delete process.env.GEMINI_API_KEY;

  try {
    const { default: handler } = (await import('../api/chat.js')) as { default: ChatHandler };

    async function ask(content: string): Promise<string> {
      const response = await handler.fetch(
        new Request('http://localhost/api/chat', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ messages: [{ role: 'user', content }] }),
        })
      );
      assert.equal(response.status, 200);
      const text = await response.text();
      assert.doesNotMatch(text, /MODULE_NOT_FOUND|assistant_unavailable/);
      return text;
    }

    const grosbit = await ask('Tu travailles chez Grosbit ?');
    assert.match(grosbit, /GROSBIT/i);
    assert.match(grosbit, /2026/);

    const edu = await ask('Quelles sont tes formations ?');
    assert.match(edu, /Lomé Business School|DEFITECH/i);

    const linkedin = await ask('Quel est ton LinkedIn ?');
    assert.match(linkedin, /linkedin\.com\/in\/chaminadeadjolou/i);

    const salary = await ask('Quelles sont tes prétentions salariales ?');
    assert.match(salary, /XOF|FCFA/i);
    assert.match(salary, /indicatif|indicative/i);

    const network = await ask('Parle-moi de son réseau GDG et PyCon');
    assert.match(network, /GDG/i);
    assert.match(network, /PyCon/i);
  } finally {
    if (prevGroq) process.env.GROQ_API_KEY = prevGroq;
    if (prevGoogle) process.env.GOOGLE_GENERATIVE_AI_API_KEY = prevGoogle;
    if (prevGemini) process.env.GEMINI_API_KEY = prevGemini;
  }
});
