<?php

declare(strict_types=1);

/**
 * Catalogue projets — aligné sur constants.tsx
 * Images servies depuis /public (chemins /fichier.png)
 */
return [
    [
        'title' => 'PICON',
        'description' => 'Application mobile innovante développée en 2026.',
        'detailed_description' => "Conception et développement d'une application mobile complète sur mesure. Elle vise à optimiser les processus d'impression de photos en ligne avec intégration de moyens de paiement et à offrir une expérience utilisateur exceptionnelle.",
        'type' => 'Mobile',
        'image' => '/picon.png',
        'link' => 'https://photopicon.vercel.app',
        'github' => 'https://github.com/Donchaminade/photopicon',
        'sort_order' => 1,
        'is_featured' => 1,
        'tags' => ['Flutter', 'Dart'],
        'additional_images' => [],
    ],
    [
        'title' => 'Tayba Market ERP',
        'description' => 'Système complet de gestion commerciale pour Tayba Market.',
        'detailed_description' => "Logiciel sur-mesure (SaaS) conçu pour digitaliser entièrement l'activité : gestion des ventes, suivi des stocks en temps réel, fidélisation clients, gestion des caissiers et clôtures de caisses.",
        'type' => 'Web',
        'image' => '',
        'link' => '#',
        'github' => '#',
        'sort_order' => 2,
        'is_featured' => 1,
        'tags' => ['React', 'Node.js', 'ERP', 'Digitalisation'],
        'additional_images' => [],
    ],
    [
        'title' => 'La 8e Tranche',
        'description' => 'Site web pour le restaurant La 8e Tranche à Lomé.',
        'detailed_description' => 'Une expérience culinaire ivoiro-togolaise authentique dans un cadre chaleureux et raffiné. Le site permet de découvrir le menu, de lire les avis et de réserver une table.',
        'type' => 'Web',
        'image' => '/resto8tranch.png',
        'link' => 'https://8-me-tranche-delights.vercel.app',
        'github' => '#',
        'sort_order' => 3,
        'is_featured' => 1,
        'tags' => ['React', 'Tailwind'],
        'additional_images' => ['/8tran.png', '/8tranch.png'],
    ],
    [
        'title' => 'RachCargo',
        'description' => "Plateforme d'expédition premium de colis par voie aérienne.",
        'detailed_description' => "Service d'expédition rapide et certifié depuis le Togo, Bénin et Ghana vers le monde entier. Transport sécurisé avec suivi de colis en temps réel.",
        'type' => 'Web',
        'image' => '/rachcar.png',
        'link' => 'https://rachcargo.vercel.app/',
        'github' => '#',
        'sort_order' => 4,
        'is_featured' => 1,
        'tags' => ['Next.js', 'Tailwind'],
        'additional_images' => ['/rachcaar.png', '/rachcarg.png'],
    ],
    [
        'title' => 'Africa Power Platform',
        'description' => "Le premier sommet dédié à Microsoft Power Platform en Afrique de l'Ouest.",
        'detailed_description' => 'Une initiative panafricaine pour éduquer, connecter et impacter (Édition 2024 - Cotonou, Bénin).',
        'type' => 'Web',
        'image' => '/afro.png',
        'link' => 'https://africapowerplateform.vercel.app/',
        'github' => '#',
        'sort_order' => 5,
        'is_featured' => 1,
        'tags' => ['React', 'Tailwind'],
        'additional_images' => ['/afroo.png', '/afrooo.png'],
    ],
    [
        'title' => 'PayFlex',
        'description' => 'Solution de paiement flexible pour les apprentis et artisans.',
        'detailed_description' => 'Plateforme innovante dédiée aux artisans pour faciliter la gestion financière et les paiements échelonnés de leurs apprentis.',
        'type' => 'Web',
        'image' => '/payf.png',
        'link' => 'https://pay-flex.vercel.app/',
        'github' => 'https://github.com/Donchaminade/PayFlex',
        'sort_order' => 6,
        'is_featured' => 0,
        'tags' => ['React', 'Tailwind'],
        'additional_images' => ['/payff.png', '/payfff.png'],
    ],
    [
        'title' => 'AI228 (Open Source)',
        'description' => 'Projet communautaire recensant les outils IA pour faciliter leur adoption au quotidien.',
        'detailed_description' => "AI228 est une plateforme centralisée conçue pour l'écosystème tech togolais. Elle agit comme un hub recensant les outils d'intelligence artificielle les plus pertinents, classés par cas d'utilisation. Le projet est entièrement open-source pour encourager la contribution locale et la transparence.",
        'type' => 'Web',
        'image' => '/ai.png',
        'link' => 'https://ai228-hub.vercel.app/',
        'github' => 'https://github.com/Donchaminade/ai228-hub/',
        'sort_order' => 7,
        'is_featured' => 0,
        'tags' => ['Github', 'Git', 'Next.js', 'Tailwind', 'json'],
        'additional_images' => ['/aib.png', '/splash.png'],
    ],
    [
        'title' => 'Nutripack',
        'description' => 'Plateforme e-Commerce de vente de produits alimentaires bio.',
        'detailed_description' => 'Nutripack est une plateforme e-commerce spécialisée dans la vente de produits alimentaires bio. Elle offre une solution simple et rapide pour les utilisateurs souhaitant acheter des produits frais et sains, avec une livraison à domicile.',
        'type' => 'Web',
        'image' => '/nutri.png',
        'link' => 'https://nutripack.vercel.app/',
        'github' => 'https://github.com/Donchaminade/nutripack/',
        'sort_order' => 8,
        'is_featured' => 0,
        'tags' => ['Next.js', 'Tailwind', 'Supabase', 'json'],
        'additional_images' => ['/nutrii.png', '/nutriii.png'],
    ],
    [
        'title' => 'Ratoufa',
        'description' => 'Solution mobile de gestion des commandes et de réservation de tickets pour événements.',
        'detailed_description' => "Développement d'une application mobile permettant la gestion des commandes et la réservation de tickets pour des événements, offrant une solution digitale fiable pour les organisateurs et une expérience simple et rapide pour les utilisateurs.",
        'type' => 'Mobile',
        'image' => '/rtf.jpeg',
        'link' => '#',
        'github' => '#',
        'sort_order' => 9,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'Agile'],
        'additional_images' => ['/rtf1.jpeg'],
    ],
    [
        'title' => 'Locafrica',
        'description' => 'Solution mobile de location des chambres/maisons et de réservation en afrique.',
        'detailed_description' => 'Développement des interfaces mobiles permettant de trouver les chambres/maisons dispo, voir sa localisation et se rendre ou de faire simplement la réservation offrant une solution rapide pour les utilisateurs.',
        'type' => 'Mobile',
        'image' => '/loca.png',
        'link' => '#',
        'github' => '#',
        'sort_order' => 10,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'Agile'],
        'additional_images' => ['/loca1.png', '/loca2.png'],
    ],
    [
        'title' => 'Axone Digital Company',
        'description' => "Mise en place du site vitrine de l'entreprise Axone Digital Company.",
        'detailed_description' => "Conception et réalisation d'un site vitrine dédié au branding de l'entreprise, mettant en valeur son identité visuelle, ses services et sa vision. Le site a été pensé pour offrir une expérience utilisateur fluide, un design moderne et une navigation claire, afin de renforcer la crédibilité de la marque et sa présence en ligne.",
        'type' => 'Web',
        'image' => '/axone.png',
        'link' => 'https://axone-digital.net/demo',
        'github' => '#',
        'sort_order' => 11,
        'is_featured' => 0,
        'tags' => ['Bootstrap', 'HTML', 'CSS', 'javascript'],
        'additional_images' => [],
    ],
    [
        'title' => 'Akontaa App',
        'description' => 'Application mobile de gestion des dettes et redevances.',
        'detailed_description' => "Conception et développement d'une application mobile dédiée à la gestion des dettes et redevances. Akontaa permet aux utilisateurs de suivre, enregistrer et organiser leurs créances de manière simple et intuitive.",
        'type' => 'Mobile',
        'image' => '/akk.jpeg',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/akontaa_v2',
        'sort_order' => 12,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'Tailwind'],
        'additional_images' => ['/ak.jpeg', '/ak1.jpeg', '/ak2.jpeg', '/ak3.jpeg', '/ak4.jpeg'],
    ],
    [
        'title' => '48 lois app vf',
        'description' => 'Application mobile des 48 lois du pouvoir de Robert Greene.',
        'detailed_description' => "Une application Anglaise existante reproduite fidèlement en Français, la toute 1ère au Togo avec des apports personnels comme des exemples concrets afin d'aider les lecteurs à mieux comprendre chaque loi, avec une fonctionnalité de notification journalière selon le paramétrage de chaque utilisateur.",
        'type' => 'Mobile',
        'image' => '/48.png',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/48laws',
        'sort_order' => 13,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart'],
        'additional_images' => ['/481.png', '/482.png', '/483.png', '/484.png', '/485.png'],
    ],
    [
        'title' => 'PROCOPE Afrique',
        'description' => 'Site vitrine du Centre Incubateur PROCOPE Afrique.',
        'detailed_description' => "Conception et personnalisation d'un site web vitrine pour le Centre Incubateur PROCOPE Afrique, à partir d'un modèle de site statique. Le site a été adapté pour répondre aux besoins spécifiques du centre, en mettant en avant sa mission, ses programmes d'incubation et ses activités.",
        'type' => 'Web',
        'image' => '/proco.png',
        'link' => 'https://www.procopeafrique.org',
        'github' => 'https://github.com/Donchaminade/procope-afrique',
        'sort_order' => 14,
        'is_featured' => 0,
        'tags' => ['HTML', 'CSS', 'JavaScript'],
        'additional_images' => ['/procoo.png', '/procooo.png'],
    ],
    [
        'title' => 'AndyKC',
        'description' => 'Site vitrine des services de consulting, accompagnement et suivis.',
        'detailed_description' => 'Site vitrine présentant les services de consulting, accompagnement et suivi professionnel.',
        'type' => 'Web',
        'image' => '/andy.png',
        'link' => 'https://andykc.com',
        'github' => 'https://github.com/Donchaminade/andykc',
        'sort_order' => 15,
        'is_featured' => 0,
        'tags' => ['React', 'Tailwind'],
        'additional_images' => ['/andyy.png'],
    ],
    [
        'title' => 'TwinFlow',
        'description' => 'Sidecar base de données : lisse les pics d’écriture PostgreSQL et sert les lectures non critiques depuis un miroir local.',
        'detailed_description' => "TwinFlow s’interpose devant PostgreSQL : pool borné, file d’écriture et miroir SQLite synchronisé en environ une seconde. API HTTP JSON, indépendante du langage. La base centrale reste la source de vérité.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://twinflow-eosin.vercel.app',
        'github' => 'https://github.com/Donchaminade/twinflow',
        'sort_order' => 16,
        'is_featured' => 1,
        'tags' => ['Go', 'PostgreSQL', 'SQLite', 'Docker'],
        'additional_images' => [],
    ],
    [
        'title' => 'Togo Communities Hub',
        'description' => 'Annuaire public qui recense, valorise et connecte les communautés du Togo.',
        'detailed_description' => "Vitrine des communautés togolaises (tech, culture, sport, citoyenneté) : fiches riches, contacts des leads, espace d’administration et signalements. Conçu pour sortir les infos des groupes WhatsApp et des liens morts.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://togo-communities-hub.vercel.app',
        'github' => 'https://github.com/Donchaminade/togo-communities-hub',
        'sort_order' => 17,
        'is_featured' => 1,
        'tags' => ['React', 'TypeScript', 'Tailwind'],
        'additional_images' => [],
    ],
    [
        'title' => 'TogoSaaS',
        'description' => 'Hub qui recense les SaaS togolais, filtrable par ville et thématique.',
        'detailed_description' => "Annuaire public des produits SaaS du Togo, avec fiches détaillées, espace lead, modération et signalements. Stack React + TypeScript côté vitrine, API PHP/MySQL.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://togosaas.vercel.app',
        'github' => 'https://github.com/Donchaminade/togosaas',
        'sort_order' => 18,
        'is_featured' => 0,
        'tags' => ['React', 'TypeScript', 'PHP', 'MySQL'],
        'additional_images' => [],
    ],
    [
        'title' => 'Optibloc',
        'description' => 'Site vitrine d’Optibloc, conçu et déployé pour présenter l’offre en ligne.',
        'detailed_description' => "Site vitrine moderne pour Optibloc : mise en avant de l’identité, des services et du parcours utilisateur, déployé sur Vercel.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://optibloc.vercel.app',
        'github' => 'https://github.com/Donchaminade/Optibloc',
        'sort_order' => 19,
        'is_featured' => 0,
        'tags' => ['React', 'TypeScript', 'Vite'],
        'additional_images' => [],
    ],
    [
        'title' => 'IEPP Tsévié',
        'description' => 'Plateforme web réalisée pour l’inspection de l’enseignement (IEPP Tsévié).',
        'detailed_description' => "Projet institutionnel pour l’IEPP Tsévié : digitalisation des processus de l’inspection et mise à disposition d’un site opérationnel.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://iepp-tsevie.vercel.app',
        'github' => 'https://github.com/Donchaminade/IEPP_TSEVIE',
        'sort_order' => 20,
        'is_featured' => 0,
        'tags' => ['HTML', 'CSS', 'JavaScript'],
        'additional_images' => [],
    ],
    [
        'title' => 'CoachFlow',
        'description' => 'Application mobile de coaching IA : personas expertes, contexte personnel et conversation vocale.',
        'detailed_description' => "CoachFlow démocratise le coaching personnel. L’utilisateur crée des personas (stoïcisme, produit, sport…), partage un contexte unique, et converse avec Llama 3.1. Offline-first (Hive), biométrie, backend Supabase. Application mobile — démo publique non publiée à ce jour.",
        'type' => 'Mobile',
        'image' => '',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/CoachFlow',
        'sort_order' => 21,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'Supabase', 'Riverpod'],
        'additional_images' => [],
    ],
    [
        'title' => 'HorusSight',
        'description' => 'Plateforme d’intelligence cybersécurité : scan, tableau de bord et rapports IA.',
        'detailed_description' => "HorusSight relie un moteur de scan Python (SQLi, XSS, SSRF…) à un centre de commande Next.js. L’assistant EWABA (Gemini) transforme les findings techniques en rapports métier. Interface bilingue FR/EN. Démo publique non publiée à ce jour.",
        'type' => 'Web',
        'image' => '',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/HorusSight',
        'sort_order' => 22,
        'is_featured' => 0,
        'tags' => ['Next.js', 'TypeScript', 'Python', 'Tailwind'],
        'additional_images' => [],
    ],
    [
        'title' => 'CredHub',
        'description' => 'Coffre-fort d’identifiants 100 % local, chiffré, mobile et web.',
        'detailed_description' => "Gestionnaire de credentials hors cloud : projets, e-mails, mots de passe, URLs et notes restent sur l’appareil. Flutter multiplateforme, chiffrement local. Aucune démo hébergée — le produit est pensé pour rester privé.",
        'type' => 'Mobile',
        'image' => '',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/CredHub',
        'sort_order' => 23,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'Sécurité'],
        'additional_images' => [],
    ],
    [
        'title' => 'ConseilBox',
        'description' => 'Application mobile de partage de conseils et d’expériences, avec API PHP.',
        'detailed_description' => "ConseilBox permet de découvrir, proposer et mettre en favoris des conseils, avec une section publicités type marketplace. Frontend Flutter, backend API PHP. Pas d’URL publique de production à ce jour.",
        'type' => 'Mobile',
        'image' => '',
        'link' => '#',
        'github' => 'https://github.com/Donchaminade/conseilbox',
        'sort_order' => 24,
        'is_featured' => 0,
        'tags' => ['Flutter', 'Dart', 'PHP'],
        'additional_images' => [],
    ],
    [
        'title' => 'Grosbit',
        'description' => 'Site web de GROSBIT, entreprise d’infrastructures et de solutions IT.',
        'detailed_description' => "Refonte du site de GROSBIT SARLU : présentation de l’entreprise, des services réseau et de l’accompagnement technique.",
        'type' => 'Web',
        'image' => '',
        'link' => 'https://grosbit.vercel.app',
        'github' => 'https://github.com/Donchaminade/grosbit',
        'sort_order' => 25,
        'is_featured' => 0,
        'tags' => ['HTML', 'CSS', 'JavaScript'],
        'additional_images' => [],
    ],
];

