<?php

/**
 * Catalogue d'icônes (Devicon / Vector Logo Zone) — seed & sync admin.
 * @see admin/technologies.php?sync=1
 */
$devicon = static fn (string $path): string => 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/' . $path;
$vlz = static fn (string $path): string => 'https://www.vectorlogo.zone/logos/' . $path;

return [
    'Android' => $devicon('android/android-original.svg'),
    'Angular' => $devicon('angularjs/angularjs-original.svg'),
    'Ansible' => $vlz('ansible/ansible-icon.svg'),
    'Apache' => $devicon('apache/apache-original.svg'),
    'AWS' => $devicon('amazonwebservices/amazonwebservices-plain-wordmark.svg'),
    'Azure' => $devicon('azure/azure-original.svg'),
    'Bootstrap' => $devicon('bootstrap/bootstrap-original.svg'),
    'Bun' => $vlz('bunjs/bunjs-icon.svg'),
    'C' => $devicon('c/c-original.svg'),
    'C#' => $devicon('csharp/csharp-original.svg'),
    'C++' => $devicon('cplusplus/cplusplus-original.svg'),
    'Canva' => $vlz('canva/canva-icon.svg'),
    'Capacitor' => $vlz('capacitorjs/capacitorjs-icon.svg'),
    'Cisco' => $vlz('cisco/cisco-icon.svg'),
    'CSS' => $devicon('css3/css3-original.svg'),
    'Cypress' => $devicon('cypressio/cypressio-original.svg'),
    'Dart' => $devicon('dart/dart-original.svg'),
    'Deno' => $devicon('denojs/denojs-original.svg'),
    'Design' => $vlz('figma/figma-icon.svg'),
    'Digitalisation' => $vlz('google_cloud/google_cloud-icon.svg'),
    'Django' => $devicon('django/django-plain.svg'),
    'Docker' => $devicon('docker/docker-original.svg'),
    'Electron' => $devicon('electron/electron-original.svg'),
    'Elixir' => $devicon('elixir/elixir-original.svg'),
    'ERP' => $vlz('oracle/oracle-icon.svg'),
    'Express.js' => $devicon('express/express-original.svg'),
    'FastAPI' => $devicon('fastapi/fastapi-original.svg'),
    'Figma' => $vlz('figma/figma-icon.svg'),
    'Firebase' => $devicon('firebase/firebase-plain.svg'),
    'Flask' => $devicon('flask/flask-original.svg'),
    'Flutter' => $devicon('flutter/flutter-original.svg'),
    'Git' => $devicon('git/git-original.svg'),
    'GitHub' => $vlz('github/github-icon.svg'),
    'GitLab' => $devicon('gitlab/gitlab-original.svg'),
    'Go' => $devicon('go/go-original-wordmark.svg'),
    'Google Cloud' => $devicon('googlecloud/googlecloud-original.svg'),
    'Gradle' => $devicon('gradle/gradle-original.svg'),
    'GraphQL' => $devicon('graphql/graphql-plain.svg'),
    'Hibernate' => $vlz('hibernate/hibernate-icon.svg'),
    'HTML' => $devicon('html5/html5-original.svg'),
    'Ionic' => $devicon('ionic/ionic-original.svg'),
    'Java' => $devicon('java/java-original.svg'),
    'JavaScript' => $devicon('javascript/javascript-original.svg'),
    'Jenkins' => $devicon('jenkins/jenkins-original.svg'),
    'Jest' => $devicon('jest/jest-plain.svg'),
    'Jira' => $vlz('atlassian_jira/atlassian_jira-icon.svg'),
    'jQuery' => $devicon('jquery/jquery-original.svg'),
    'JSON' => $devicon('json/json-original.svg'),
    'JUnit' => $devicon('junit/junit-original.svg'),
    'Kafka' => $devicon('apachekafka/apachekafka-original.svg'),
    'Kotlin' => $devicon('kotlin/kotlin-original.svg'),
    'Kubernetes' => $devicon('kubernetes/kubernetes-plain.svg'),
    'Laravel' => $devicon('laravel/laravel-original.svg'),
    'Linux' => $devicon('linux/linux-original.svg'),
    'Maven' => $vlz('apache_maven/apache_maven-icon.svg'),
    'MariaDB' => $devicon('mariadb/mariadb-original.svg'),
    'MongoDB' => $devicon('mongodb/mongodb-original.svg'),
    'MySQL' => $devicon('mysql/mysql-original.svg'),
    'NestJS' => $devicon('nestjs/nestjs-plain.svg'),
    'Next.js' => $devicon('nextjs/nextjs-original.svg'),
    'Nginx' => $devicon('nginx/nginx-original.svg'),
    'Node.js' => $devicon('nodejs/nodejs-original.svg'),
    'Nuxt.js' => $devicon('nuxtjs/nuxtjs-original.svg'),
    'OpenAPI' => $vlz('openapi/openapi-icon.svg'),
    'Oracle' => $devicon('oracle/oracle-original.svg'),
    'PHP' => $devicon('php/php-original.svg'),
    'PostgreSQL' => $devicon('postgresql/postgresql-original.svg'),
    'Postman' => $vlz('postman/postman-icon.svg'),
    'Prisma' => $vlz('prisma/prisma-icon.svg'),
    'Python' => $devicon('python/python-original.svg'),
    'RabbitMQ' => $vlz('rabbitmq/rabbitmq-icon.svg'),
    'React' => $devicon('react/react-original.svg'),
    'React Native' => $devicon('react/react-original.svg'),
    'Redis' => $devicon('redis/redis-original.svg'),
    'Redux' => $devicon('redux/redux-original.svg'),
    'Remote' => $vlz('zoom/zoom-icon.svg'),
    'Ruby' => $devicon('ruby/ruby-original.svg'),
    'Ruby on Rails' => $devicon('rails/rails-plain-wordmark.svg'),
    'Rust' => $devicon('rust/rust-plain.svg'),
    'Sass' => $devicon('sass/sass-original.svg'),
    'Scala' => $devicon('scala/scala-original.svg'),
    'Spring' => $devicon('spring/spring-original.svg'),
    'Spring Boot' => $devicon('spring/spring-original-wordmark.svg'),
    'SQLite' => $devicon('sqlite/sqlite-original.svg'),
    'Supabase' => $vlz('supabase/supabase-icon.svg'),
    'Svelte' => $devicon('svelte/svelte-original.svg'),
    'Symfony' => $devicon('symfony/symfony-original.svg'),
    'Tailwind CSS' => $vlz('tailwindcss/tailwindcss-icon.svg'),
    'Terraform' => $devicon('terraform/terraform-original.svg'),
    'TypeScript' => $devicon('typescript/typescript-original.svg'),
    'Unity' => $devicon('unity/unity-original.svg'),
    'Unreal Engine' => $devicon('unrealengine/unrealengine-original.svg'),
    'Vite' => $devicon('vitejs/vitejs-original.svg'),
    'Vue.js' => $devicon('vuejs/vuejs-original.svg'),
    'Webpack' => $devicon('webpack/webpack-original.svg'),
    'WordPress' => $devicon('wordpress/wordpress-plain.svg'),
    'Xamarin' => $vlz('xamarin/xamarin-icon.svg'),
    '.NET' => $devicon('dot-net/dot-net-original.svg'),
    'Agile' => $vlz('atlassian_jira/atlassian_jira-icon.svg'),
    'Management' => $vlz('slack/slack-icon.svg'),
    'VS Code' => $devicon('vscode/vscode-original.svg'),
    // Alias rétrocompatibilité
    'Tailwind' => $vlz('tailwindcss/tailwindcss-icon.svg'),
    'VScode' => $devicon('vscode/vscode-original.svg'),
    'json' => $devicon('json/json-original.svg'),
];
