export type Lang = 'fr' | 'en';

const fr = {
  langGroup: 'Langue du site',
  skip: 'Aller au contenu',
  navMain: 'Principale',
  navMobile: 'Navigation mobile',
  navFooter: 'Pied de page',
  openMenu: 'Ouvrir le menu',
  closeMenu: 'Fermer le menu',
  themeLight: 'Passer en thème clair',
  themeDark: 'Passer en thème sombre',
  contactCta: 'Me contacter',
  links: {
    profile: 'Profil',
    about: 'À propos',
    stack: 'Stack',
    projects: 'Projets',
    path: 'Parcours',
    community: 'Communauté',
    references: 'Références',
    blog: 'Blog',
    contact: 'Contact',
    cv: 'CV',
  },
  rights: 'Tous droits réservés',
  book: 'Réserver un appel',
  book30: 'Réserver un appel de 30 min',
  seeProjects: 'Voir mes projets',
  downloadCv: 'Télécharger le CV',
  cvLang: 'Langue du CV',
  socials: 'Réseaux',
  photoAlt: (name: string) => `${name} au travail sur son ordinateur`,
  factsLabel: 'Repères',
  stackKicker: 'Stack',
  stackTitle: 'Ce que j’utilise en production',
  stackLead: 'Regroupé par domaine. Chaque techno renvoie à au moins un projet livré.',
  projectsKicker: 'Projets',
  projectsTitle: 'Réalisations récentes',
  projectsLead: 'Fiches du catalogue en ligne : titre, description, technologies et liens.',
  seeAll: (n: number) => `Voir les ${n} projets`,
  filterProjects: 'Filtrer les projets',
  filters: { all: 'Tous', web: 'Web', mobile: 'Mobile', backend: 'Backend', oss: 'Open source' },
  detail: 'Description détaillée',
  pathKicker: 'Parcours',
  pathTitle: 'Expérience',
  cvKicker: 'CV',
  cvTitle: 'Mon CV, en français ou en anglais',
  cvMeta: (role: string, updated: string) => `${role} · 2 pages · PDF texte · mis à jour en ${updated}.`,
  cvFrName: 'CV Full-Stack',
  cvEnName: 'CV Full-Stack',
  download: 'Télécharger',
  openPreview: 'Ouvrir l’aperçu dans un nouvel onglet',
  updated: 'octobre 2026',
  communityKicker: 'Communautés',
  communityTitle: 'Là où je m’implique',
  communityLead: 'Un engagement actif pour l’écosystème tech local.',
  discover: 'Lire le rôle',
  close: 'Fermer',
  website: 'Site',
  aboutKicker: 'À propos',
  aboutTitle: 'Formation, savoir-être et distinctions',
  aboutLead: 'Le détail du profil : études, soft skills et prix réellement obtenus.',
  education: 'Formation',
  softSkills: 'Savoir-être',
  awards: 'Distinctions',
  seeMore: 'Voir plus',
  seeLess: 'Voir moins',
  pagesKicker: 'Pages',
  pagesTitle: 'Communautés que j’anime en ligne',
  pagesLead: 'Pages et vitrines dont je m’occupe.',
  followers: 'abonnés',
  trustKicker: 'Confiance',
  trustTitle: 'Ils m’ont fait confiance',
  trustLead: 'Logos des collaborations réelles. Aucun visuel de banque d’images.',
  proofKicker: 'Retours',
  proofTitle: 'Ce que disent les collaborations',
  proofLead: 'Témoignages relus avant publication, et recommandations.',
  leaveTestimonial: 'Laisser un témoignage',
  leaveRecommendation: 'Laisser une recommandation',
  emptyTestimonials: 'Aucun témoignage publié pour le moment. Le premier peut venir de vous.',
  emptyRecommendations: 'Aucune recommandation publiée pour le moment.',
  proofFilters: 'Filtrer les retours',
  allProof: 'Tout',
  testimonials: 'Témoignages',
  recommendations: 'Recommandations',
  contactKicker: 'Contact',
  contactTitle: 'Un projet, un poste, une mission ?',
  contactLead: 'Écrivez-moi ou réservez directement un créneau de 30 minutes.',
  writeEmail: 'Écrire un e-mail',
  propose: 'Proposer une collaboration',
  name: 'Nom',
  email: 'E-mail',
  message: 'Message',
  send: 'Envoyer le message',
  sending: 'Envoi…',
  formInvalid: 'Indiquez un nom, un e-mail et un message d’au moins 10 caractères.',
  sendFail: 'Envoi impossible pour le moment.',
  sent: 'Message envoyé. Je vous réponds bientôt.',
  catalog: 'Catalogue',
  projectCount: (n: number) => `${n} projets`,
  filterCatalog: 'Filtrer le catalogue',
  backHome: 'Retour à l’accueil',
  privateProject: 'Projet privé ou confidentiel',
  nda: 'Certains projets restent sous accord de confidentialité.',
  concept: 'Le concept',
  technologies: 'Technologies',
  linkHeading: 'Liens',
  closeProject: 'Fermer la fiche projet',
  blogKicker: 'Le blog',
  blogTitleBefore: 'Idées, tech et ',
  blogTitleEm: 'équilibre',
  blogTitleAfter: ', écrits depuis Lomé',
  blogLead: 'Essais en français et, lorsqu’ils existent, leur version anglaise : développement, agents IA, énergie et engagement.',
  searchLabel: 'Rechercher un article',
  searchPlaceholder: 'Rechercher un article…',
  blogIllu: 'Illustration : carnet d’articles, code et idées',
  categories: 'Catégories',
  all: 'Tous',
  loadingPosts: 'Chargement des articles…',
  loadError: 'Impossible de charger les articles.',
  featured: 'À la une',
  read: 'Lire l’article',
  latest: 'Derniers articles',
  readNext: 'À lire ensuite',
  minRead: (n: number) => `${n} min de lecture`,
  minutes: (n: number) => `${n} min`,
  noMatch: 'Aucun article ne correspond.',
  loadMore: 'Charger plus d’articles',
  series: 'Séries',
  explore: 'Explorer par thème',
  seriesAgents: 'Agents et IA',
  seriesAgentsSub: 'Outils, harness, MCP',
  seriesCloud: 'Cloud et DevOps',
  seriesCloudSub: 'Cloudflare, Docker, CI',
  seriesBalance: 'Équilibre',
  seriesBalanceSub: 'Lâcher prise, santé mentale',
  seriesCivic: 'Engagement',
  seriesCivicSub: 'Bénévolat, communautés',
  frenchOnly: 'Article available in French',
  frenchOnlyLead: 'This article does not have an English version yet. Switch to FR to read it.',
  loadingArticle: 'Chargement de l’article…',
  missingArticle: 'Article introuvable',
  apiMissing: 'API non configurée.',
  backBlog: 'Retour au blog',
  crumbs: 'Fil d’Ariane',
  views: (n: number) => `${n} vues`,
  writtenBy: 'Écrit par Chaminade Adjolou',
  writtenRole: 'Développeur Full-Stack Web et Mobile à Lomé.',
  previewBanner: 'Aperçu brouillon — non publié. Relisez, puis validez dans l’admin.',
  toTop: 'Retour en haut',
  toc: 'Sommaire',
  tocParts: (n: number) => `Sommaire · ${n} parties`,
  copy: 'Copier',
  copied: 'Copié',
  copyFail: 'Impossible',
  share: 'Partager',
  shareArticle: 'Partager cet article',
  shareVia: 'Partager via',
  copyLink: 'Copier le lien',
  linkCopied: 'Lien copié.',
  shared: 'Partage enregistré.',
  shareFail: 'Partage impossible pour le moment.',
  likeFail: 'Impossible d’enregistrer le like pour le moment.',
  discussion: 'Discussion',
  messageCount: (n: number) => (n <= 1 ? `${n} message` : `${n} messages`),
  discussionLead: 'Publiez ou répondez : le message apparaît tout de suite.',
  firstComment: 'Soyez le premier à lancer la discussion.',
  newComment: 'Nouveau commentaire',
  yourName: 'Votre nom',
  commentPlaceholder: 'Partagez votre avis sur cet article…',
  publish: 'Publier',
  commentSent: 'Commentaire publié.',
  sendError: 'Envoi impossible.',
  reply: 'Répondre',
  cancel: 'Annuler',
  replyTo: 'En réponse à',
  yourReply: 'Votre réponse…',
  loading: 'Chargement…',
  chatOpen: 'Ouvrir l’assistant portfolio',
  chatClose: 'Fermer l’assistant',
  chatTitle: 'Assistant Donchaminade',
  chatLead: 'Questions sur le profil, les projets, le parcours et les articles publics.',
  chatHello: 'Bonjour — je peux parler du parcours, de PyCon Togo, du coaching YAS / Next Gen, des projets et des derniers articles. Hors sujet, je passerai mon tour.',
  chatWriting: 'Rédaction en cours…',
  chatError: 'Impossible de répondre pour le moment. Réessayez.',
  chatNote: 'Réponses à partir du contenu public du portfolio. Les échanges ne sont pas conservés.',
  chatAsk: 'Votre question',
  chatPlaceholder: 'Ex. Quels sont tes projets ?',
  chatSend: 'Envoyer le message',
  suggestions: [
    'Quels sont tes projets ?',
    'Quelles sont tes prétentions salariales ?',
    'Quelle est sa valeur ajoutée ?',
    'Parle-moi de son réseau',
  ],
  seoTitle: (name: string) => `${name} — Développeur Full-Stack Web et Mobile`,
  seoFallback: 'Portfolio de Chaminade Adjolou, développeur full-stack web et mobile à Lomé.',
  blogSeoTitle: 'Blog — Chaminade Adjolou',
  blogSeoDesc: 'Articles de Chaminade Adjolou, depuis Lomé.',
  modalTestimonial: 'Laisser un témoignage',
  modalTestimonialLead: 'Votre texte sera relu avant publication.',
  modalRecommendation: 'Laisser une recommandation',
  modalRecommendationLead: 'Une note et un message, publiés après envoi.',
  quote: 'Témoignage',
  role: 'Fonction',
  company: 'Entreprise',
  photo: 'Photo',
  photoOptional: 'Photo (optionnel)',
  rating: 'Votre note',
  minChars: '30 caractères minimum…',
  submit: 'Envoyer',
  publishShort: 'Publier',
  apiDown: 'L’API n’est pas joignable pour le moment.',
  sentModeration: 'Merci. Le témoignage sera relu avant publication.',
  sentRecommendation: 'Merci. La recommandation a été envoyée.',
  chooseRating: 'Choisissez une note entre 1 et 5.',
  closeDialog: 'Fermer',
  collabTitle: 'Collaborons',
  collabLead: 'Décrivez votre projet — je vous recontacte rapidement.',
  phone: 'Téléphone',
  org: 'Entreprise / organisation',
  subject: 'Objet de la collaboration',
  subjectPh: 'Ex. Refonte d’un site, application mobile…',
  need: 'Décrivez votre besoin en détail',
  needPh: 'Type de projet, objectifs, délais, technologies souhaitées…',
  docs: 'J’ai des documents à partager (cahier des charges, maquettes…)',
  addFiles: 'Cliquez pour ajouter des fichiers',
  fileHint: (n: number, mb: number) => `PDF, Word, PowerPoint, Excel, images — ${n} fichiers maximum, ${mb} Mo chacun`,
  remove: 'Retirer',
  notePh: 'Note optionnelle (lien, précisions…)',
  slot: 'Proposer un créneau pour en discuter',
  platform: 'Plateforme',
  slotWhen: 'Date et heure',
  slotN: (n: number) => `Créneau ${n}`,
  removeSlot: 'Supprimer ce créneau',
  addSlot: 'Ajouter un autre créneau',
  notes: 'Notes (optionnel)',
  notesPh: 'Durée souhaitée, fuseau horaire, langue de l’échange…',
  sendRequest: 'Envoyer ma demande',
  collabSent: 'Demande envoyée. Je vous recontacte.',
  fileTooBig: (name: string, mb: number) => `${name} dépasse ${mb} Mo.`,
  platforms: {
    google_meet: 'Google Meet',
    zoom: 'Zoom',
    teams: 'Microsoft Teams',
    whatsapp: 'WhatsApp',
    phone: 'Appel téléphonique',
    other: 'Autre',
  },
  stars: (n: number) => `${n} étoile${n > 1 ? 's' : ''}`,
  bookFloat: 'Réserver',
  availableNow: 'Disponible pour de nouveaux défis',
  cvAlternate: 'CV en anglais',
  commentFrench: 'Commentaire disponible en français',
  author: 'Auteur',
  choose: 'Choisir…',
  maxFiles: (n: number) => `Maximum ${n} fichiers.`,
  docsMissing: 'Ajoutez au moins un fichier ou une note sur vos documents.',
  serviceDown: 'Service temporairement indisponible.',
  slotDate: 'Date et heure',
  sizeUnit: 'Mo',
};

const en: typeof fr = {
  langGroup: 'Site language',
  skip: 'Skip to content',
  navMain: 'Primary',
  navMobile: 'Mobile navigation',
  navFooter: 'Footer',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  themeLight: 'Switch to light theme',
  themeDark: 'Switch to dark theme',
  contactCta: 'Contact me',
  links: {
    profile: 'Profile',
    about: 'About',
    stack: 'Stack',
    projects: 'Projects',
    path: 'Career',
    community: 'Community',
    references: 'References',
    blog: 'Blog',
    contact: 'Contact',
    cv: 'CV',
  },
  rights: 'All rights reserved',
  book: 'Book a call',
  book30: 'Book a 30-minute call',
  seeProjects: 'See my projects',
  downloadCv: 'Download CV',
  cvLang: 'CV language',
  socials: 'Social profiles',
  photoAlt: (name: string) => `${name} working at a computer`,
  factsLabel: 'Highlights',
  stackKicker: 'Stack',
  stackTitle: 'What I use in production',
  stackLead: 'Grouped by area. Each technology maps to at least one shipped project.',
  projectsKicker: 'Projects',
  projectsTitle: 'Recent work',
  projectsLead: 'Live catalogue cards: title, description, technologies and links.',
  seeAll: (n: number) => `See all ${n} projects`,
  filterProjects: 'Filter projects',
  filters: { all: 'All', web: 'Web', mobile: 'Mobile', backend: 'Backend', oss: 'Open source' },
  detail: 'Full description',
  pathKicker: 'Career',
  pathTitle: 'Experience',
  cvKicker: 'CV',
  cvTitle: 'My CV, in French or in English',
  cvMeta: (role: string, updated: string) => `${role} · 2 pages · text PDF · updated ${updated}.`,
  cvFrName: 'Full-Stack CV',
  cvEnName: 'Full-Stack résumé',
  download: 'Download',
  openPreview: 'Open the preview in a new tab',
  updated: 'October 2026',
  communityKicker: 'Communities',
  communityTitle: 'Where I contribute',
  communityLead: 'Active work in the local tech ecosystem.',
  discover: 'Read the role',
  close: 'Close',
  website: 'Website',
  aboutKicker: 'About',
  aboutTitle: 'Education, strengths and awards',
  aboutLead: 'Studies, soft skills and awards that were actually received.',
  education: 'Education',
  softSkills: 'Soft skills',
  awards: 'Awards',
  seeMore: 'See more',
  seeLess: 'See less',
  pagesKicker: 'Pages',
  pagesTitle: 'Communities I help run online',
  pagesLead: 'Pages and showcases I look after.',
  followers: 'followers',
  trustKicker: 'Trust',
  trustTitle: 'Teams I have worked with',
  trustLead: 'Logos from real collaborations. No stock photography.',
  proofKicker: 'Feedback',
  proofTitle: 'What collaborations say',
  proofLead: 'Testimonials are reviewed before they go live. Recommendations too.',
  leaveTestimonial: 'Leave a testimonial',
  leaveRecommendation: 'Leave a recommendation',
  emptyTestimonials: 'No testimonial has been published yet. Yours can be the first.',
  emptyRecommendations: 'No recommendation has been published yet.',
  proofFilters: 'Filter feedback',
  allProof: 'All',
  testimonials: 'Testimonials',
  recommendations: 'Recommendations',
  contactKicker: 'Contact',
  contactTitle: 'A product, a role, a mission?',
  contactLead: 'Write to me or book a 30-minute slot directly.',
  writeEmail: 'Send an email',
  propose: 'Propose a collaboration',
  name: 'Name',
  email: 'Email',
  message: 'Message',
  send: 'Send message',
  sending: 'Sending…',
  formInvalid: 'Enter a name, an email and a message of at least 10 characters.',
  sendFail: 'The message could not be sent right now.',
  sent: 'Message sent. I will reply soon.',
  catalog: 'Catalogue',
  projectCount: (n: number) => `${n} projects`,
  filterCatalog: 'Filter the catalogue',
  backHome: 'Back to home',
  privateProject: 'Private or confidential project',
  nda: 'Some projects stay under a confidentiality agreement.',
  concept: 'The idea',
  technologies: 'Technologies',
  linkHeading: 'Links',
  closeProject: 'Close project details',
  blogKicker: 'The blog',
  blogTitleBefore: 'Ideas, tech and ',
  blogTitleEm: 'balance',
  blogTitleAfter: ', written from Lomé',
  blogLead: 'Essays, and their English version when one exists: software, AI agents, energy and commitment.',
  searchLabel: 'Search articles',
  searchPlaceholder: 'Search articles…',
  blogIllu: 'Illustration: a notebook of articles, code and ideas',
  categories: 'Categories',
  all: 'All',
  loadingPosts: 'Loading articles…',
  loadError: 'The articles could not be loaded.',
  featured: 'Featured',
  read: 'Read article',
  latest: 'Latest articles',
  readNext: 'Read next',
  minRead: (n: number) => `${n} min read`,
  minutes: (n: number) => `${n} min`,
  noMatch: 'No article matches.',
  loadMore: 'Load more articles',
  series: 'Series',
  explore: 'Browse by theme',
  seriesAgents: 'Agents and AI',
  seriesAgentsSub: 'Tools, harness, MCP',
  seriesCloud: 'Cloud and DevOps',
  seriesCloudSub: 'Cloudflare, Docker, CI',
  seriesBalance: 'Balance',
  seriesBalanceSub: 'Letting go, mental health',
  seriesCivic: 'Commitment',
  seriesCivicSub: 'Volunteering, communities',
  frenchOnly: 'Article available in French',
  frenchOnlyLead: 'This article does not have an English version yet. Switch to FR to read it.',
  loadingArticle: 'Loading article…',
  missingArticle: 'Article not found',
  apiMissing: 'API is not configured.',
  backBlog: 'Back to the blog',
  crumbs: 'Breadcrumb',
  views: (n: number) => `${n} views`,
  writtenBy: 'Written by Chaminade Adjolou',
  writtenRole: 'Full-stack web and mobile developer in Lomé.',
  previewBanner: 'Draft preview — not published. Review it, then approve it in the admin.',
  toTop: 'Back to top',
  toc: 'Contents',
  tocParts: (n: number) => `Contents · ${n} parts`,
  copy: 'Copy',
  copied: 'Copied',
  copyFail: 'Failed',
  share: 'Share',
  shareArticle: 'Share this article',
  shareVia: 'Share via',
  copyLink: 'Copy link',
  linkCopied: 'Link copied.',
  shared: 'Share recorded.',
  shareFail: 'Sharing is unavailable right now.',
  likeFail: 'The like could not be saved right now.',
  discussion: 'Discussion',
  messageCount: (n: number) => (n === 1 ? `${n} message` : `${n} messages`),
  discussionLead: 'Post or reply: the message shows up immediately.',
  firstComment: 'Be the first to start the discussion.',
  newComment: 'New comment',
  yourName: 'Your name',
  commentPlaceholder: 'Share your thoughts on this article…',
  publish: 'Publish',
  commentSent: 'Comment published.',
  sendError: 'Could not send.',
  reply: 'Reply',
  cancel: 'Cancel',
  replyTo: 'In reply to',
  yourReply: 'Your reply…',
  loading: 'Loading…',
  chatOpen: 'Open the portfolio assistant',
  chatClose: 'Close the assistant',
  chatTitle: 'Donchaminade assistant',
  chatLead: 'Questions about the profile, projects, career and public articles.',
  chatHello: 'Hello — I can talk about the career path, PyCon Togo, YAS / Next Gen coaching, projects and the latest articles. Off-topic questions, I will pass.',
  chatWriting: 'Writing…',
  chatError: 'I cannot answer right now. Please try again.',
  chatNote: 'Answers come from the public portfolio. Conversations are not stored.',
  chatAsk: 'Your question',
  chatPlaceholder: 'e.g. What are your projects?',
  chatSend: 'Send message',
  suggestions: [
    'What are your projects?',
    'What are your salary expectations?',
    'What extra value does this profile bring?',
    'Tell me about the network',
  ],
  seoTitle: (name: string) => `${name} — Full-Stack Web & Mobile Developer`,
  seoFallback: 'Portfolio of Chaminade Adjolou, full-stack web and mobile developer in Lomé.',
  blogSeoTitle: 'Blog — Chaminade Adjolou',
  blogSeoDesc: 'Articles by Chaminade Adjolou, from Lomé.',
  modalTestimonial: 'Leave a testimonial',
  modalTestimonialLead: 'Your text is reviewed before it is published.',
  modalRecommendation: 'Leave a recommendation',
  modalRecommendationLead: 'A rating and a message, sent for publication.',
  quote: 'Testimonial',
  role: 'Role',
  company: 'Company',
  photo: 'Photo',
  photoOptional: 'Photo (optional)',
  rating: 'Your rating',
  minChars: '30 characters minimum…',
  submit: 'Send',
  publishShort: 'Publish',
  apiDown: 'The API cannot be reached right now.',
  sentModeration: 'Thank you. The testimonial will be reviewed before publication.',
  sentRecommendation: 'Thank you. The recommendation was sent.',
  chooseRating: 'Choose a rating from 1 to 5.',
  closeDialog: 'Close',
  collabTitle: 'Let’s collaborate',
  collabLead: 'Describe your project — I will get back to you shortly.',
  phone: 'Phone',
  org: 'Company / organisation',
  subject: 'Collaboration subject',
  subjectPh: 'e.g. Website rebuild, mobile app…',
  need: 'Describe what you need',
  needPh: 'Project type, goals, timing, technologies…',
  docs: 'I have documents to share (brief, mockups…)',
  addFiles: 'Click to add files',
  fileHint: (n: number, mb: number) => `PDF, Word, PowerPoint, Excel, images — up to ${n} files, ${mb} MB each`,
  remove: 'Remove',
  notePh: 'Optional note (link, details…)',
  slot: 'Suggest a time to talk',
  platform: 'Platform',
  slotWhen: 'Date and time',
  slotN: (n: number) => `Slot ${n}`,
  removeSlot: 'Remove this slot',
  addSlot: 'Add another slot',
  notes: 'Notes (optional)',
  notesPh: 'Preferred length, timezone, language…',
  sendRequest: 'Send my request',
  collabSent: 'Request sent. I will get back to you.',
  fileTooBig: (name: string, mb: number) => `${name} is over ${mb} MB.`,
  platforms: {
    google_meet: 'Google Meet',
    zoom: 'Zoom',
    teams: 'Microsoft Teams',
    whatsapp: 'WhatsApp',
    phone: 'Phone call',
    other: 'Other',
  },
  stars: (n: number) => `${n} star${n > 1 ? 's' : ''}`,
  bookFloat: 'Book',
  availableNow: 'Available for new challenges',
  cvAlternate: 'French CV',
  commentFrench: 'Comment available in French',
  author: 'Author',
  choose: 'Choose…',
  maxFiles: (n: number) => `Up to ${n} files.`,
  docsMissing: 'Add at least one file or a note about your documents.',
  serviceDown: 'The service is temporarily unavailable.',
  slotDate: 'Date and time',
  sizeUnit: 'MB',
};

export const copy = { fr, en };
export type Copy = typeof fr;
