ALTER TABLE blog_posts MODIFY COLUMN category VARCHAR(48) NOT NULL DEFAULT 'tech';

CREATE TABLE IF NOT EXISTS blog_category_labels (
  slug VARCHAR(48) PRIMARY KEY,
  label VARCHAR(80) NOT NULL,
  emoji VARCHAR(12) NOT NULL DEFAULT '📝',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
